### ISSUE TITLE
Not possible to open .md files added to Dropbox from other app

### ISSUE THREAD

**Issue by matiasvillaverde** [landakram/kiwi#15]
With the new version 2.0 is not possible to add .md files from Dropbox. I am creating .md files (kiwi pages) with a desktop computer and when i try to open them on Kiwi app, nothing is happening.  Do you think is possible to upload a hotfix to the store?  Thanks in advance

**Comment by landakram** [comment]
Thanks for the heads-up. I'll take a look at this this weekend. 

Question: 

How are you actually trying to open the file in kiwi? And what is the behavior exactly? Does the app crash?

**Comment by landakram** [comment]
@matiasvillaverde, I'm not able to reproduce this. Here's what I'm trying: 

1. In an editor on my computer, I create a `.md` file and save it to `Dropbox/Apps/KiwiApp/wiki`
2. I open the app on my phone
3. I tap the title to get to the "All Pages" view
4. I see the new page listed and tap on it
5. The new page is rendered

Are you seeing something different?

**Comment by matiasvillaverde** [comment]
@landakram Thanks for checking this. Yours steps are working perfect, I just check it and is working for me as well. But if I create the .md files somewhere else (in my case Github wiki) and I paste it into `Dropbox/Apps/KiwiApp/wiki` is not working. 

Here's what I'm trying: 
1. I create a `Test.md` page in Github wiki
2. Clone the wiki repository to my computer
3. Copy paste `Test.md` file into `Dropbox/Apps/KiwiApp/wiki`
4. I tap the title to get to "All Pages" view
5. I see the new file `Test.md` and tapo on it
6. The page is not rendered and shows `home.md`

**Comment by shauxesis** [comment]
@landakram I’ve just purchase Kiwi with the hope it could read .md files from my Dropbox created in nvALT on my MacBook Pro. However I’m having the same problem, paste a bunch of .md files into Kiwi folder, they sync with app and I can see them however I can’t open them as pages. I tried creating [[links]] to a couple of these notes in the Home page, but when I click the link is doesn’t navigate to the document/page, rather it prompts me to create a new page. I’d be grateful for your help as Kiwi is literally the closest app I’ve come across that is perfect for use with nvALT and [[links]]. As it it, the app is unusable (can’t even search context of notes that’s have synced from Dropbox). Please help.

**Comment by matiasvillaverde** [comment]
@landakram would be great to have some support here :)

**Comment by landakram** [comment]
@shauxexis, thanks for reporting! 

Last time, I couldn’t reproduce this issue using the steps that @matiasvillaverde so kindly outlined. 

Could you please provide precise steps to reproduce like Matias did above including the names of the NValt files? That would go a long way toward helping me fix this issue. Would love to make this work for you!

**Comment by landakram** [comment]
@shauxesis, thanks for reporting! 

Last time, I couldn’t reproduce this issue using the steps that @matiasvillaverde so kindly outlined. 

Could you please provide precise steps to reproduce like Matias did above including the names of the NValt files? That would go a long way toward helping me fix this issue. Would love to make this work for you!

**Comment by shauxesis** [comment]
@landakram thank you so much for your reply. Your help would be greatly appreciated. Would it be easier to email you a quick time of the process so you can see what is happening in real-time rather than trying to decipher my explanation? I'm happy to do either way. Let me know.   
  

  
  

  
  
>

**Comment by landakram** [comment]
@shauxesis, a video would be really helpful! You can send it to me@markhudnall.com or drop a link to it here.

**Comment by landakram** [comment]
@shauxesis, @matiasvillaverde I was able to reproduce and fixed the issue in https://github.com/landakram/kiwi/pull/19. You should be seeing the update in the App Store as soon as Apple approves it.

**Comment by shauxesis** [comment]
Hey Mark,

That's excellent news! I have been trying to figure out how to record my screen on my iPhone for you with little luck. But here's what I did find: naming a text file in lowercase and with underscores between words was the only way to make the app recognise the text files created on the Mac. Then a rather convoluted process of using hazel to rename 'A Text File' to 'a_text_file' and moving it to the kiwi folder, which was then monitored as any changes synced back to the nvalt folder. I gave up in the end as my hack sync process wasn't very reliable. Has the fix you've implemented now allowed for all naming conversions? Will it read a name with spaces and title case? I look forward to the update. Thank you for all your hard work, much appreciated! Shande

**Comment by matiasvillaverde** [comment]
@landakram Great news!! Definitely you will get 5 stars on the AppStore, thanks a lot! 

But there is still one bug, the links to pages do not support all the file names. So even that I can open .md is not possible to link them. Should I open another issue? Thanks in advance

**Comment by Fr3d-P** [comment]
It seems that the style of names that Kiwi now accepts doesn't include CamelCase names, however it is used in wikis, and trunksync had that sort of file names. Could Kiwi be updated to open AWikiPage.md ?
