### ISSUE TITLE
Support links for different file types 

### ISSUE THREAD

**Issue by matiasvillaverde** [landakram/kiwi#20]
### Expected behaviour 
Integrate Kiwi with different types of file format. Principally to support Github Wiki that are base in the [Gollum Wiki](https://github.com/gollum/gollum/wiki) format. To accomplish this Kiwi app should link to files with any of the following: a_wiki_page.md, A Wiki Page.md, A wiki page.md, A_Wiki_Page.md, A_wiki_page.md

### Current behaviour 
We open this [issue](https://github.com/landakram/kiwi/issues/15) because was not possible to open files that they don´t have the same format of kiwi app. Now is possible to read this files, but the links pointing to a different format, for example [[Page Name]], are not working.

### Steps to reproduce the bug
1. Manually add one file to the kiwi dropbox folder called "Test-Github-Format.md"
2. Kiwi will be able to open this file, but is not possible to link it in another page.
3. For example we can add a link [[Test Github Format]] to the home.md 
3. Kiwi will not recognise that link and will try to create a new file called Text_Github_Format.md.

This feature will allow us to use Kiwi together with Github Wiki, Gollum Wiki and other types of wikis based on markdown. Thanks in advance!

**Comment by landakram** [comment]
As of https://github.com/landakram/kiwi/commit/b05d4985374e9ff927749fb6f66c7e33b7537722, a few more file names are supported. 

The full list of supported file names is [here](https://github.com/landakram/kiwi/blob/b05d4985374e9ff927749fb6f66c7e33b7537722/Kiwi/Wiki.swift#L136-L143).
