### ISSUE TITLE
Paste Causing Crashes

### ISSUE THREAD

**Issue by andyspurgeon** [landakram/kiwi#21]
Hello, purchased Kiwi last night and enjoy using it. Noticed a bug, however, when trying to cut/paste from external applications. I observed this bug when trying to paste from Safari, Notes, and Pages. The original content causing the crash was from Safari (a paragraph with embedded links). I thought perhaps the links were causing the crash, so I tried removing them in Notes and it still crashed. I then tried a paragraph from Pages just to test, and that crashed too.

Would be much more useful if cut/paste worked. :)

Specs:
  * iPad Air 64 Gb (old)
  * iOS 11.2.2

**Comment by as-miller** [comment]
The app is also crashing for me when pasting anything at all. 

iPhone 7+ 
IOS 11.2.2

**Comment by landakram** [comment]
Thanks for the report y’all. I experienced this as well, and it looks like
a crash introduced in iOS 11. I’ll be looking into it this weekend.

**Comment by jasonmaskell** [comment]
Hi

I purchased this recently, and LOVE it! But am having this issue also.

iPhone 6
iOS 11.3

**Comment by landakram** [comment]
Fixed in https://github.com/landakram/kiwi/pull/30 (in kind of a heavy-handed way, but whatevs). 

Release will be going out to the app store shortly!
