### ISSUE TITLE
RFMarkdownTextView Deprecated

### ISSUE THREAD

**Issue by matiasvillaverde** [landakram/kiwi#6]
I tried to run pod install but MarkdownTextView is no longer available. Check [Notepad](https://github.com/ruddfawcett/Notepad), a new Swift 3.0 Markdown editor.

[!] No podspec found for `RFMarkdownTextView` in `~/Documents/code/Memex/RFMarkdownTextView`

**Comment by landakram** [comment]
Thanks for the report. I saw Notepad, but haven't had time to do the migration. 

I'll look into it for the next release. I started a new job but things have stabilized and I've put it some work to upgrade the Dropbox SDK to V2 and refactor some of the code, which should make changes like this easier to make :P

**Comment by landakram** [comment]
@matiasvillaverde, the switch to Notepad is in `master` now and will be going out soon in the next app update.
